apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: metallb-hcloud-controller
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  requiredDropCapabilities:
  - ALL
  volumes:
  - secret
  fsGroup:
    ranges:
      - max: 65535
        min: 1
    rule: MustRunAs
  runAsUser:
    ranges:
      - max: 65535
        min: 1
    rule: MustRunAs
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
      - max: 65535
        min: 1
    rule: MustRunAs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metallb-hcloud-controller
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - metallb-hcloud-controller
- apiGroups: ['']
  # List, watch and get services to be able to extract
  # LoadBalancer IP address from the service.
  # #
  resources: ['services']
  verbs: ['get', 'list', 'watch']
- apiGroups: ['']
  # List watch and get events to be able to follow
  # MetalLB node announcement events.
  resources: ['events']
  verbs: ['get', 'list', 'watch']
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metallb-hcloud-controller
subjects:
- kind: ServiceAccount
  name: metallb-hcloud-controller
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: metallb-hcloud-controller
  apiGroup: rbac.authorization.k8s.io
