apiVersion: v1
kind: Service
metadata:
  name: metallb-hcloud-controller
  labels:
    app: metallb-hcloud-controller
spec:
  ports:
  - port: 2112
    protocol: TCP
    name: metrics-http
  selector:
    app: metallb-hcloud-controller
